apiVersion: v1
kind: Service
metadata:
  namespace: fraud-detection-namespace
  name: fraud-service
  labels:
    app-label: fraud-detection-app-label
spec:
  ports:
    - port: 80
      name: http
      targetPort: 80
  selector:
    app-label: fraud-detection-app-label
  type: LoadBalancer
