apiVersion: v1
kind: Service
metadata:
  namespace: fraud-detection-namespace
  name: fraud-service
  labels:
    app-label: fraud-detection-app-label
spec:
  ports:
    - name: fraud
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app-label: fraud-detection-app-label
  type: LoadBalancer
